import { Prisma } from '@prisma/client';

export const roomSeed: Prisma.RoomCreateManyInput[] = [
  {
    id: 1,
    name: 'Premier',
    property_id: 1,
    base_price: 920000,
    description: '',
    capacity: 2,
    size: 32,
    total_room: 40,
  },
  {
    id: 2,
    name: 'Arya Suite',
    property_id: 1,
    base_price: 1800000,
    description: '',
    capacity: 2,
    size: 50,
    total_room: 20,
  },
  {
    id: 3,
    name: 'Deluxe',
    property_id: 2,
    base_price: 980000,
    description:
      'Classic, fully equipped with high quality furniture and amenities. A 40sqm room equipped with Wi-Fi, TV cable with channel options, safe deposit box and working desk. Free buffet breakfast and daily newspaper.     Bed Type : King Bed (220cm x 200cm) / Twin Bed (140cm x 200cm)  *Bedding requested is subject to availability of hotel',
    capacity: 2,
    size: 40,
    total_room: 44,
  },
  {
    id: 4,
    name: 'Family Suite',
    property_id: 2,
    base_price: 2400000,
    description:
      'A room for the family fully equipped with high-quality furniture and amenities, the bathroom comes with a bathtub and shower. A 70sqm unit equipped for 2(two) rooms Wi-Fi, TV cable with channel options, safe deposit box, and working desk. Free buffet breakfast for 4(four) persons and daily newspaper.     Bed Type: 2 room with King Bed (220cm x 200cm)',
    capacity: 4,
    size: 70,
    total_room: 25,
  },
  {
    id: 5,
    name: 'Superior',
    property_id: 3,
    base_price: 442000,
    description:
      'Available in one and two single beds, our Superior Rooms blend comfort with affordability and convenience.',
    capacity: 2,
    size: 23,
    total_room: 20,
  },
  {
    id: 6,
    name: 'Deluxe',
    property_id: 3,
    base_price: 585000,
    description:
      '24 unit Kamar Deluxe yang luas di hotel ini adalah pilihan ideal untuk pelancong bisnis dan liburan. Tamu dapat memilih kamar dengan satu atau dua tempat tidur single. Menampilkan fasilitas dan layanan yang hebat, kamar-kamar ini ditawarkan dalam paket nilai yang terjangkau.',
    capacity: 2,
    size: 31,
    total_room: 24,
  },
  {
    id: 7,
    name: 'Superior',
    property_id: 4,
    base_price: 390000,
    description:
      'Set in 19 sqm modern and stylish room comes with a personal safe, flat-screen TV with satellite channels, Individually controlled Air Conditioning, Work Desk and Shower. You can request either double or twin bedding upon selecting your dates of stay. This room does not fit an extra bed.',
    capacity: 2,
    size: 19,
    total_room: 18,
  },
  {
    id: 8,
    name: 'Suite',
    property_id: 4,
    base_price: 1060000,
    description:
      'The 96sqm comfortable sanctuary for business, leisure or family travelers when visiting Medan city. Featuring high quality amenities expected from an international standard hotel with 3-star facilities, The Suite Room delivers a suave atmosphere you expect to come home when you are away from home',
    capacity: 2,
    size: 96,
    total_room: 10,
  },
  {
    id: 9,
    name: '1 King Bed Deluxe',
    property_id: 5,
    base_price: 1390000,
    description: '1 King Bed, 484 - sq - foot room with city views',
    capacity: 2,
    size: 45,
    total_room: 50,
  },
  {
    id: 10,
    name: '1 King Bed Executive',
    property_id: 5,
    base_price: 2350000,
    description: '1 King Bed, 700 - sq - foot room with city views',
    capacity: 2,
    size: 65,
    total_room: 30,
  },
  {
    id: 11,
    name: 'Deluxe',
    property_id: 6,
    base_price: 880000,
    description:
      'The deluxe room features king ( Doubled Bed ) or Twin bed  LCD TV, safe deposit box, writing desk, wireless internet.',
    capacity: 2,
    size: 29,
    total_room: 46,
  },
  {
    id: 12,
    name: 'Cityhall Suite',
    property_id: 6,
    base_price: 1470000,
    description:
      'This 55m2 carpeted non smoking suite with a king size bed, LCD TV, hair dryer and free internet access with adjoining living room to offers you a high level of comfort.',
    capacity: 2,
    size: 55,
    total_room: 26,
  },
  {
    id: 13,
    name: 'Deluxe With 2 Single Beds',
    property_id: 7,
    base_price: 680000,
    description:
      'Spacious room of 387.5 sq.ft. (36.8 m²), combining comfort and space with two single beds, 1 single seater sofa, writing desk, in-room safe deposit, Cable TV channels, in-room minibar, bathtub and shower, and hair dryer.',
    capacity: 2,
    size: 42,
    total_room: 40,
  },
  {
    id: 14,
    name: 'Premiere With 2 Single Beds',
    property_id: 7,
    base_price: 900000,
    description:
      'Spacious room with 38 m², comfortable two single beds, feather Duvet \u0026 Pillow, Bedroom Slippers, shower, Toiletries, Lounge Chair \u0026 Table, 42 inch TV, coffee / tea making facility, Fridge, Writing Desk, and Safe Deposit.',
    capacity: 2,
    size: 42,
    total_room: 38,
  },
  {
    id: 15,
    name: 'Superior With 2 Single Beds',
    property_id: 8,
    base_price: 446000,
    description:
      'The 23.8m² modern and stylish Superior room features wireless Internet, LED TV, connectivity plug, mini bar, bathroom with shower and tea and coffee making facilities.',
    capacity: 2,
    size: 24,
    total_room: 14,
  },
  {
    id: 16,
    name: 'Superior With 1 Double Bed',
    property_id: 8,
    base_price: 430000,
    description:
      'The 23.8m² modern and stylish Superior room features wireless Internet, LED TV, connectivity plug, mini bar, bathroom with shower and tea and coffee making facilities.',
    capacity: 2,
    size: 24,
    total_room: 15,
  },
  {
    id: 17,
    name: 'Reddoorz Family',
    property_id: 9,
    base_price: 291000,
    description: '',
    capacity: 2,
    size: 22,
    total_room: 8,
  },
  {
    id: 18,
    name: 'Reddoorz',
    property_id: 9,
    base_price: 285000,
    description: '',
    capacity: 2,
    size: 20,
    total_room: 10,
  },
  {
    id: 19,
    name: 'Superior Twin',
    property_id: 10,
    base_price: 232000,
    description: '',
    capacity: 2,
    size: 20,
    total_room: 10,
  },
  {
    id: 20,
    name: 'Deluxe',
    property_id: 10,
    base_price: 269000,
    description: '',
    capacity: 2,
    size: 24,
    total_room: 10,
  },
  {
    id: 21,
    name: 'Studio Premier',
    property_id: 11,
    base_price: 1490000,
    description: '',
    capacity: 2,
    size: 50,
    total_room: 17,
  },
  {
    id: 22,
    name: 'Bedroom Premier 1',
    property_id: 11,
    base_price: 1740000,
    description: '',
    capacity: 2,
    size: 80,
    total_room: 15,
  },
  {
    id: 23,
    name: 'Studio Executive',
    property_id: 12,
    base_price: 1050000,
    description:
      'Designed for executives and international travellers on either a business trips or holidays in search of serviced studio apartment in Jakarta, the Studio Executive apartments are well-furnished with modern amenities. These serviced apartments offer a queen-size bed, refrigerator, internet access, air conditioning and daily housekeeping service. Breakfast for children aged 7 to 11 years will be subject to an additional charge of 50% of the breakfast price. Children aged 12 years and older will be considered adults.',
    capacity: 2,
    size: 23,
    total_room: 20,
  },
  {
    id: 24,
    name: 'Bedroom Deluxe King One',
    property_id: 12,
    base_price: 1200000,
    description:
      'Enjoy generous living and dining area with contemporary furniture, when you reside at these furnished apartments in Jakarta for entertaining or relaxing after a long day of adventure in the city. The air-conditioning, complimentary Wi-Fi access, housekeeping amenities, as well as modern furnishing and equipment are within your reach.',
    capacity: 2,
    size: 41,
    total_room: 18,
  },
  {
    id: 25,
    name: 'Villa Segar Ii Five Bedroom Private Pool',
    property_id: 13,
    base_price: 2293000,
    description:
      'Share quality time when traveling with family or friends in a comfortable sanctuary within an area of 550 square meters. Adorned with fine furnishings, soft linens, and creative interior ornaments, our Five-Bedroom Villa will reassure you and never lose your togetherness or intimacy. Such delightful ambiance confidently ensures you unwind smoothly at the end of your holiday activities in a private space encapsulated with all the luxuries and facilities The Catur Villa has to offer. No party is allowed in the Villa to keep the tranquil atmosphere of the Villa.',
    capacity: 12,
    size: 550,
    total_room: 5,
  },
  {
    id: 26,
    name: 'Villa Segar Six Bedroom Private Pool',
    property_id: 13,
    base_price: 2457000,
    description:
      'Share quality time when traveling with family or friends in a comfortable sanctuary within an area of 500 square meters. Adorned with fine furnishings, soft linens, and creative interior ornaments, our Six-Bedroom Villa will reassure you and never lose your togetherness or intimacy. Such delightful ambiance confidently ensures you unwind smoothly at the end of your holiday activities in a private space encapsulated with all the luxuries and facilities The Catur Villa has to offer. No party is allowed in the Villa to keep the tranquil atmosphere of the Villa.',
    capacity: 14,
    size: 500,
    total_room: 5,
  },
  {
    id: 27,
    name: 'One Bedroom Villa Private Pool',
    property_id: 14,
    base_price: 675000,
    description:
      'One Bedroom Deluxe Pool Villa One Bedroom Deluxe Pool Villa Free Area Shuttle to Sanur, Sukawati, Keramas Beach.',
    capacity: 2,
    size: 115,
    total_room: 6,
  },
  {
    id: 28,
    name: 'One Bedroom Junior Suite Pool Villa',
    property_id: 14,
    base_price: 920000,
    description:
      'One Bedroom Suite Pool Villa One Bedroom Suite Pool Villa.Free Area Shuttle to Sanur, Sukawati, Keramas Beach.',
    capacity: 2,
    size: 115,
    total_room: 6,
  },
  {
    id: 29,
    name: 'One-bedroom Villa - Private Pool',
    property_id: 15,
    base_price: 908000,
    description:
      'One Bedroom Deluxe Pool Villa One Bedroom Deluxe Pool Villa Free Area Shuttle to Sanur, Sukawati, Keramas Beach.',
    capacity: 2,
    size: 40,
    total_room: 10,
  },
  {
    id: 30,
    name: 'Two-bedroom Villa - Private Pool',
    property_id: 15,
    base_price: 1515000,
    description: 'Two-bedroom Villa with Private Pool',
    capacity: 4,
    size: 50,
    total_room: 8,
  },
  {
    id: 31,
    name: 'One Bedroom Villa - Private Pool',
    property_id: 16,
    base_price: 758000,
    description: 'One Bedroom Private Pool Villa',
    capacity: 2,
    size: 150,
    total_room: 7,
  },
  {
    id: 32,
    name: 'Two Bedroom Villa Private Pool',
    property_id: 16,
    base_price: 2000000,
    description: 'Two Bedroom Private Pool Villa Include Breakfast',
    capacity: 4,
    size: 300,
    total_room: 5,
  },
  {
    id: 33,
    name: '1 Bedroom Pool Villa',
    property_id: 17,
    base_price: 1545000,
    description: 'One Bedroom Pool Villa',
    capacity: 2,
    size: 70,
    total_room: 10,
  },
  {
    id: 34,
    name: '2 Bedroom Pool Villa',
    property_id: 17,
    base_price: 2894000,
    description: 'Two Bedroom Pool Villa',
    capacity: 4,
    size: 170,
    total_room: 10,
  },
  {
    id: 35,
    name: 'Deluxe',
    property_id: 18,
    base_price: 707000,
    description:
      'Terletak di belakang bangunan utama properti, kamar double atau twin ini menawarkan privasi lebih dengan desain yang elegan. Saat ini kami sedang menjalankan proyek di sebelah bangunan. Beberapa kebisingan akan memengaruhi selama jam kerja dan mungkin memengaruhi pengalaman Anda.',
    capacity: 2,
    size: 27,
    total_room: 24,
  },
  {
    id: 36,
    name: 'Executive Balcony',
    property_id: 18,
    base_price: 1113000,
    description:
      'Located in the front building overlooking Kuta Beach. The Executive Balcony provide selection double bed or twin bed comfortably sleeps two guests with balcony partially overlook to Kuta Beach. You will appreciate the convenience of a sitting area with a desk, miniature refrigerator, safe deposit box and complimentary Wi-Fi.',
    capacity: 2,
    size: 37,
    total_room: 20,
  },
  {
    id: 37,
    name: 'Junior Suite',
    property_id: 19,
    base_price: 889000,
    description:
      'Junior Suite, a cool, clean and comfy 52 sqm guest rooms where everything is designed to be highly efficient in both in terms of function and maintenance.',
    capacity: 2,
    size: 52,
    total_room: 15,
  },
  {
    id: 38,
    name: 'Family Suite',
    property_id: 19,
    base_price: 1278000,
    description:
      'The largest and most exclusive room, designed modernly to make your family holiday more enjoyable and completed with the best quality amenities in town. The room features elegant room and bathroom amenities, and complimentary high speed WiFi internet access also available to make your stay memorable.',
    capacity: 4,
    size: 113,
    total_room: 10,
  },
  {
    id: 39,
    name: 'Deluxe Pool View',
    property_id: 20,
    base_price: 497000,
    description:
      'Indulge in our stylish 28 sqm Deluxe Rooms equipped with an LCD TV, modern wardrobe, safe deposit box, coffee \u0026 tea maker, and complimentary Wi-Fi. Ideal for both business and family trips in Denpasar.',
    capacity: 2,
    size: 28,
    total_room: 20,
  },
  {
    id: 40,
    name: 'Family Suite',
    property_id: 20,
    base_price: 1138000,
    description:
      'Our Family Suite Room offer spacious space of room that start from 62 sqm. The room is perfect for family holidays and provides ample space with total 3 rooms, 1 Queen Bed with 1 Single bed in each room, sofa, minibar, coffee and tea maker and dining table plus high speed Wi-Fi internet access.',
    capacity: 3,
    size: 75,
    total_room: 5,
  },
  {
    id: 41,
    name: 'Standard',
    property_id: 21,
    base_price: 294000,
    description: '',
    capacity: 2,
    size: 16,
    total_room: 10,
  },
  {
    id: 42,
    name: 'Superior',
    property_id: 21,
    base_price: 335000,
    description: '',
    capacity: 2,
    size: 25,
    total_room: 6,
  },
  {
    id: 43,
    name: 'Executive Double',
    property_id: 22,
    base_price: 483000,
    description:
      'Executive Room. Best room option for couple at Pension Guest House.',
    capacity: 2,
    size: 17,
    total_room: 6,
  },
  {
    id: 44,
    name: 'Family',
    property_id: 22,
    base_price: 647000,
    description:
      'Kamar Family adalah pilihan terbaik untuk tinggal bersama keluarga tercinta. Dapat memuat sampai dengan 3 orang dewasa.',
    capacity: 3,
    size: 24,
    total_room: 6,
  },
  {
    id: 45,
    name: 'Deluxe Akomodasi',
    property_id: 23,
    base_price: 270000,
    description: '',
    capacity: 3,
    size: 24,
    total_room: 7,
  },
  {
    id: 46,
    name: 'Superior Akomodasi',
    property_id: 23,
    base_price: 339000,
    description: '',
    capacity: 4,
    size: 22,
    total_room: 5,
  },
  {
    id: 47,
    name: 'Standard Studio',
    property_id: 24,
    base_price: 532000,
    description: 'Single Villa',
    capacity: 2,
    size: 10,
    total_room: 5,
  },
  {
    id: 48,
    name: 'Deluxe Two Bedroom',
    property_id: 24,
    base_price: 1064000,
    description: '',
    capacity: 4,
    size: 12,
    total_room: 5,
  },
  {
    id: 49,
    name: 'Studio 25 Double Bed',
    property_id: 25,
    base_price: 204000,
    description: 'A room with kitchen',
    capacity: 2,
    size: 24.5,
    total_room: 10,
  },
  {
    id: 50,
    name: 'Studio 31 New',
    property_id: 25,
    base_price: 245000,
    description: 'New furnish room',
    capacity: 2,
    size: 31,
    total_room: 10,
  },
  {
    id: 51,
    name: 'Studio',
    property_id: 26,
    base_price: 294000,
    description: 'Hadir untuk para tamu yang ingin menginap bersama dua orang',
    capacity: 2,
    size: 24,
    total_room: 16,
  },
  {
    id: 52,
    name: 'Family',
    property_id: 26,
    base_price: 245000,
    description:
      'Hadir secara khusus untuk keluarga atau para tamu yang ingin menginap bersama dua orang lebih dengan 2 kamar tidur',
    capacity: 4,
    size: 48,
    total_room: 10,
  },
  {
    id: 53,
    name: 'Deluxe King',
    property_id: 27,
    base_price: 404000,
    description: 'One double bed or two single beds Based on Availability.',
    capacity: 2,
    size: 20,
    total_room: 15,
  },
  {
    id: 54,
    name: 'Executive King City View',
    property_id: 27,
    base_price: 604000,
    description: 'One double or twin bed based on availability.',
    capacity: 2,
    size: 30,
    total_room: 15,
  },
  {
    id: 55,
    name: 'Executive Twin',
    property_id: 28,
    base_price: 585000,
    description: 'Executive Twin Room',
    capacity: 2,
    size: 26,
    total_room: 18,
  },
  {
    id: 56,
    name: 'Executive Triple',
    property_id: 28,
    base_price: 778000,
    description: 'Executive Triple Room',
    capacity: 3,
    size: 26,
    total_room: 14,
  },
  {
    id: 57,
    name: 'Business Twin',
    property_id: 29,
    base_price: 997000,
    description:
      'Business Rooms measuring 26 square meters, and comprising a main bedroom and bathroom. These rooms are available with king and twin-sized beds and are equipped with contemporary amenities, including a safe deposit box, television, hot and cold water shower, 24-hour Wi-Fi access, tea, and coffee-making facilities, a working desk, and stunning views of Surabaya city.',
    capacity: 2,
    size: 26,
    total_room: 20,
  },
  {
    id: 59,
    name: 'Junior Suite',
    property_id: 30,
    base_price: 1870000,
    description:
      'Kick back and relax at our elevated Junior Suite room. Experience the new, comfortable and classic design of our 38,5sqm room with the best flavors of peranakan breakfast.',
    capacity: 2,
    size: 38,
    total_room: 40,
  },
  {
    id: 58,
    name: 'Deluxe Twin',
    property_id: 29,
    base_price: 1133000,
    description:
      'Deluxe Room spanning a generous 30 square meters, slightly more spacious than the Business Room option. The Deluxe Rooms offer a main bedroom and bathroom, complete with king and twin-sized beds, and an array of modern amenities. These amenities include a safe deposit box, television, hot and cold water shower, around-the-clock Wi-Fi access, tea and coffee-making facilities, a working desk, a minibar, and breathtaking views of the city of Surabaya.',
    capacity: 2,
    size: 30,
    total_room: 20,
  },
  {
    id: 60,
    name: 'Premium Suite 1 King Bed',
    property_id: 30,
    base_price: 3070000,
    description:
      '1 King Bed, 689-sq-foot room with city views. Layout - Bedroom, living room, and dining area. Internet - Free WiFi. Entertainment - 49-inch LED TV with premium channels. Food & Drink - Electric kettle, free bottled water,  free tea bags/instant coffee, and dining table. Sleep - Frette Italian linens, blackout drapes/curtains, and bed sheets. Bathroom - Private bathroom, bathrobes, and a separate bathtub and shower with a rainfall showerhead',
    capacity: 2,
    size: 64,
    total_room: 34,
  },
];
