export enum BookingStatus {
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  WAITING_FOR_CONFIRMATION = 'WAITING_FOR_CONFIRMATION',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  DONE = 'DONE',
}
